# vi: set ft=ansible :
---
- name: Ensure monit is installed
  yum: name=monit enablerepo=epel state=present

- name: Ensure monit service is enabled
  service: name=monit enabled=yes

- name: Copy monit config file
  template: src=monitrc.j2 dest={{ monit_conf_path }} backup=no owner=root group=root mode=0600
  notify:
  - restart monit

