# vim: set ft=ansible :

---
- name: Copy iptables rules file
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

# - name: Ensure sshd commented lines are removed
#   lineinfile: dest=/etc/ssh/sshd_config state=absent 
#   notify: restart sshd

- name: Ensure sshd is secure
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - state: absent
      regexp: "^#"
      line: ""
    - state: present
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - state: present
      regexp: "^X11Forwarding"
      line: "X11Forwarding no"
    - state: present
      regexp: "^UsePAM"
      line: "UsePAM no"
  notify: restart sshd

- name: Ensure Fail2ban is installed
  yum: name=fail2ban enablerepo=epel state=present

- name: Copy fail2ban.conf to fail2ban.local
  command: cp -f /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
  notify: restart fail2ban

# todo: automatic security updates
