# vim: set ft=ansible :
---
- name: Ensure libselinux-python is installed
  yum: name=libselinux-python state=present

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Copy the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Ensure Vim is installed
  yum: name=vim enablerepo=epel state=present
