# vi: set ft=ansible :
---
- name: Create deploy group
  group: name=deploy system=yes state=present

- name: Create admin group
  group: name=admin system=yes state=present

- name: Copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.bak.{{ ansible_date_time["epoch"] }}

- name: Ensure we can sudo as deploy group
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%deploy' line='%deploy ALL=(ALL) ALL'

- name: Ensure we can sudo as admin group
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^%admin' line='%admin ALL=(ALL) ALL'

- name: Ensure ssh-agent works via sudo
  lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

- name: Final sudoers file check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: Create deploy user
  user: name=deploy groups=deploy,admin shell=/bin/bash

- name: Add authorized key
  authorized_key: user=deploy key="{{ item }}"
  with_file:
    - id_rsa.pub

# todo: deploy user password
# todo: disable passwordless sudo and create passwordless devops user
