# vi: set ft=ansible :
---
monit_conf_path: /etc/monit.conf
monit_conf_dir: /etc/monit.d
monit_poll_period: 60
monit_enable_emails: false
monit_notify_emails: []
monit_minimize_alerts: true
monit_mailserver_host: ''
monit_mailserver_port: 2812
monit_mailserver_username: 'username'
monit_mailserver_password: 'password'
monit_mailserver_hostname: 'hostname'
monit_web_interface_allow: [
# username, password
]
