---
- hosts: webservers
  sudo: yes

  vars_files:
    - vars.yml

  roles:
    - common
    - security
    - deploy-user
    - date-and-time
    - rails-gem-dependencies
    - role: geerlingguy.ruby
      ruby_install_from_source: true
      ruby_download_url: "http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz"
      ruby_version: 2.2.2
      ruby_install_gems:
      - bundler
    - role: Stouts.nodejs
      nodejs_version: 0.12.2

  # tasks:
    # - name: Install app dependencies.
    #   apt: "name={{ item }} state=present"
    #   with_items:
    #     - libsqlite3-dev
    #     - libreadline-dev

    # - name: Ensure app directory exists and is writeable.
    #   file:
    #     path: "{{ app_directory }}"
    #     state: directory
    #     owner: "{{ app_user }}"
    #     group: "{{ app_user }}"
    #     mode: 0755
